// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: zhitongAgent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ZhitongAgent_ChatStream_FullMethodName  = "/zhitongagent.v1.ZhitongAgent/ChatStream"
	ZhitongAgent_AgentStream_FullMethodName = "/zhitongagent.v1.ZhitongAgent/AgentStream"
)

// ZhitongAgentClient is the client API for ZhitongAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ZhitongAgent 提供普通流和 Agent 流两种 gRPC 服务。
type ZhitongAgentClient interface {
	// ChatStream 使用 minichain 的 InitChatModel 创建普通流并按事件持续返回。
	ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	// AgentStream 使用 minichain 的 CreateAgent 创建 Agent 流并按事件持续返回。
	AgentStream(ctx context.Context, in *AgentStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
}

type zhitongAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewZhitongAgentClient(cc grpc.ClientConnInterface) ZhitongAgentClient {
	return &zhitongAgentClient{cc}
}

func (c *zhitongAgentClient) ChatStream(ctx context.Context, in *ChatStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZhitongAgent_ServiceDesc.Streams[0], ZhitongAgent_ChatStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatStreamRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZhitongAgent_ChatStreamClient = grpc.ServerStreamingClient[StreamResponse]

func (c *zhitongAgentClient) AgentStream(ctx context.Context, in *AgentStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ZhitongAgent_ServiceDesc.Streams[1], ZhitongAgent_AgentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentStreamRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZhitongAgent_AgentStreamClient = grpc.ServerStreamingClient[StreamResponse]

// ZhitongAgentServer is the server API for ZhitongAgent service.
// All implementations must embed UnimplementedZhitongAgentServer
// for forward compatibility.
//
// ZhitongAgent 提供普通流和 Agent 流两种 gRPC 服务。
type ZhitongAgentServer interface {
	// ChatStream 使用 minichain 的 InitChatModel 创建普通流并按事件持续返回。
	ChatStream(*ChatStreamRequest, grpc.ServerStreamingServer[StreamResponse]) error
	// AgentStream 使用 minichain 的 CreateAgent 创建 Agent 流并按事件持续返回。
	AgentStream(*AgentStreamRequest, grpc.ServerStreamingServer[StreamResponse]) error
	mustEmbedUnimplementedZhitongAgentServer()
}

// UnimplementedZhitongAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedZhitongAgentServer struct{}

func (UnimplementedZhitongAgentServer) ChatStream(*ChatStreamRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method ChatStream not implemented")
}
func (UnimplementedZhitongAgentServer) AgentStream(*AgentStreamRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method AgentStream not implemented")
}
func (UnimplementedZhitongAgentServer) mustEmbedUnimplementedZhitongAgentServer() {}
func (UnimplementedZhitongAgentServer) testEmbeddedByValue()                      {}

// UnsafeZhitongAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZhitongAgentServer will
// result in compilation errors.
type UnsafeZhitongAgentServer interface {
	mustEmbedUnimplementedZhitongAgentServer()
}

func RegisterZhitongAgentServer(s grpc.ServiceRegistrar, srv ZhitongAgentServer) {
	// If the following call panics, it indicates UnimplementedZhitongAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ZhitongAgent_ServiceDesc, srv)
}

func _ZhitongAgent_ChatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZhitongAgentServer).ChatStream(m, &grpc.GenericServerStream[ChatStreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZhitongAgent_ChatStreamServer = grpc.ServerStreamingServer[StreamResponse]

func _ZhitongAgent_AgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AgentStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ZhitongAgentServer).AgentStream(m, &grpc.GenericServerStream[AgentStreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ZhitongAgent_AgentStreamServer = grpc.ServerStreamingServer[StreamResponse]

// ZhitongAgent_ServiceDesc is the grpc.ServiceDesc for ZhitongAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZhitongAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zhitongagent.v1.ZhitongAgent",
	HandlerType: (*ZhitongAgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatStream",
			Handler:       _ZhitongAgent_ChatStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AgentStream",
			Handler:       _ZhitongAgent_AgentStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "zhitongAgent.proto",
}
