// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: zhitongAgent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message 表示一次对话消息，与 minichain 的 Message 保持一致。
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolCallId    string                 `protobuf:"bytes,3,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,4,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_zhitongAgent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_zhitongAgent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_zhitongAgent_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

// ToolCallFunction 表示模型返回的函数调用信息。
type ToolCallFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,2,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallFunction) Reset() {
	*x = ToolCallFunction{}
	mi := &file_zhitongAgent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallFunction) ProtoMessage() {}

func (x *ToolCallFunction) ProtoReflect() protoreflect.Message {
	mi := &file_zhitongAgent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallFunction.ProtoReflect.Descriptor instead.
func (*ToolCallFunction) Descriptor() ([]byte, []int) {
	return file_zhitongAgent_proto_rawDescGZIP(), []int{1}
}

func (x *ToolCallFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallFunction) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// ToolCall 表示模型返回的一次工具调用。
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Function      *ToolCallFunction      `protobuf:"bytes,3,opt,name=function,proto3" json:"function,omitempty"`
	Index         int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_zhitongAgent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_zhitongAgent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_zhitongAgent_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolCall) GetFunction() *ToolCallFunction {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *ToolCall) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// ToolFunction 表示工具定义信息。
type ToolFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    *structpb.Struct       `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolFunction) Reset() {
	*x = ToolFunction{}
	mi := &file_zhitongAgent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolFunction) ProtoMessage() {}

func (x *ToolFunction) ProtoReflect() protoreflect.Message {
	mi := &file_zhitongAgent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolFunction.ProtoReflect.Descriptor instead.
func (*ToolFunction) Descriptor() ([]byte, []int) {
	return file_zhitongAgent_proto_rawDescGZIP(), []int{3}
}

func (x *ToolFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolFunction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolFunction) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// ToolDefinition 表示一项可调用工具。
type ToolDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Function      *ToolFunction          `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_zhitongAgent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_zhitongAgent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_zhitongAgent_proto_rawDescGZIP(), []int{4}
}

func (x *ToolDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolDefinition) GetFunction() *ToolFunction {
	if x != nil {
		return x.Function
	}
	return nil
}

// StreamOptions 表示流式输出附加配置。
type StreamOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeUsage  bool                   `protobuf:"varint,1,opt,name=include_usage,json=includeUsage,proto3" json:"include_usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamOptions) Reset() {
	*x = StreamOptions{}
	mi := &file_zhitongAgent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOptions) ProtoMessage() {}

func (x *StreamOptions) ProtoReflect() protoreflect.Message {
	mi := &file_zhitongAgent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamOptions.ProtoReflect.Descriptor instead.
func (*StreamOptions) Descriptor() ([]byte, []int) {
	return file_zhitongAgent_proto_rawDescGZIP(), []int{5}
}

func (x *StreamOptions) GetIncludeUsage() bool {
	if x != nil {
		return x.IncludeUsage
	}
	return false
}

// Usage 表示 token 用量统计，与 minichain 保持一致。
type Usage struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens            int64                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens        int64                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens             int64                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	PromptTokensDetails     *structpb.Struct       `protobuf:"bytes,4,opt,name=prompt_tokens_details,json=promptTokensDetails,proto3" json:"prompt_tokens_details,omitempty"`
	CompletionTokensDetails *structpb.Struct       `protobuf:"bytes,5,opt,name=completion_tokens_details,json=completionTokensDetails,proto3" json:"completion_tokens_details,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_zhitongAgent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_zhitongAgent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_zhitongAgent_proto_rawDescGZIP(), []int{6}
}

func (x *Usage) GetPromptTokens() int64 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int64 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Usage) GetPromptTokensDetails() *structpb.Struct {
	if x != nil {
		return x.PromptTokensDetails
	}
	return nil
}

func (x *Usage) GetCompletionTokensDetails() *structpb.Struct {
	if x != nil {
		return x.CompletionTokensDetails
	}
	return nil
}

// ChatStreamRequest 表示普通流请求，只保留用户输入文本。
type ChatStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamRequest) Reset() {
	*x = ChatStreamRequest{}
	mi := &file_zhitongAgent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamRequest) ProtoMessage() {}

func (x *ChatStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhitongAgent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamRequest.ProtoReflect.Descriptor instead.
func (*ChatStreamRequest) Descriptor() ([]byte, []int) {
	return file_zhitongAgent_proto_rawDescGZIP(), []int{7}
}

func (x *ChatStreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AgentStreamRequest 表示 Agent 流请求，只保留用户输入文本。
type AgentStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStreamRequest) Reset() {
	*x = AgentStreamRequest{}
	mi := &file_zhitongAgent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStreamRequest) ProtoMessage() {}

func (x *AgentStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_zhitongAgent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStreamRequest.ProtoReflect.Descriptor instead.
func (*AgentStreamRequest) Descriptor() ([]byte, []int) {
	return file_zhitongAgent_proto_rawDescGZIP(), []int{8}
}

func (x *AgentStreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StreamResponse 表示服务端流事件，并在结束时携带完整 summary。
type StreamResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventType        string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ToolName         string                 `protobuf:"bytes,3,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolArgs         string                 `protobuf:"bytes,4,opt,name=tool_args,json=toolArgs,proto3" json:"tool_args,omitempty"`
	FinishReason     string                 `protobuf:"bytes,5,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	IsFinal          bool                   `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Error            string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	ToolCalls        []*ToolCall            `protobuf:"bytes,8,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	Usage            *Usage                 `protobuf:"bytes,9,opt,name=usage,proto3" json:"usage,omitempty"`
	Id               string                 `protobuf:"bytes,10,opt,name=id,proto3" json:"id,omitempty"`
	ModelName        string                 `protobuf:"bytes,11,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	AdditionalKwargs *structpb.Struct       `protobuf:"bytes,12,opt,name=additional_kwargs,json=additionalKwargs,proto3" json:"additional_kwargs,omitempty"`
	ResponseMetadata *structpb.Struct       `protobuf:"bytes,13,opt,name=response_metadata,json=responseMetadata,proto3" json:"response_metadata,omitempty"`
	UsageMetadata    *structpb.Struct       `protobuf:"bytes,14,opt,name=usage_metadata,json=usageMetadata,proto3" json:"usage_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_zhitongAgent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_zhitongAgent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_zhitongAgent_proto_rawDescGZIP(), []int{9}
}

func (x *StreamResponse) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *StreamResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StreamResponse) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *StreamResponse) GetToolArgs() string {
	if x != nil {
		return x.ToolArgs
	}
	return ""
}

func (x *StreamResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *StreamResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *StreamResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StreamResponse) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *StreamResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *StreamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *StreamResponse) GetAdditionalKwargs() *structpb.Struct {
	if x != nil {
		return x.AdditionalKwargs
	}
	return nil
}

func (x *StreamResponse) GetResponseMetadata() *structpb.Struct {
	if x != nil {
		return x.ResponseMetadata
	}
	return nil
}

func (x *StreamResponse) GetUsageMetadata() *structpb.Struct {
	if x != nil {
		return x.UsageMetadata
	}
	return nil
}

var File_zhitongAgent_proto protoreflect.FileDescriptor

const file_zhitongAgent_proto_rawDesc = "" +
	"\n" +
	"\x12zhitongAgent.proto\x12\x0fzhitongagent.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x93\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12 \n" +
	"\ftool_call_id\x18\x03 \x01(\tR\n" +
	"toolCallId\x128\n" +
	"\n" +
	"tool_calls\x18\x04 \x03(\v2\x19.zhitongagent.v1.ToolCallR\ttoolCalls\"D\n" +
	"\x10ToolCallFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x02 \x01(\tR\targuments\"\x83\x01\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12=\n" +
	"\bfunction\x18\x03 \x01(\v2!.zhitongagent.v1.ToolCallFunctionR\bfunction\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\"}\n" +
	"\fToolFunction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\"_\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x129\n" +
	"\bfunction\x18\x02 \x01(\v2\x1d.zhitongagent.v1.ToolFunctionR\bfunction\"4\n" +
	"\rStreamOptions\x12#\n" +
	"\rinclude_usage\x18\x01 \x01(\bR\fincludeUsage\"\x9e\x02\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x03R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x03R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x03R\vtotalTokens\x12K\n" +
	"\x15prompt_tokens_details\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x13promptTokensDetails\x12S\n" +
	"\x19completion_tokens_details\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x17completionTokensDetails\"-\n" +
	"\x11ChatStreamRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x12AgentStreamRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xbc\x04\n" +
	"\x0eStreamResponse\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\x03 \x01(\tR\btoolName\x12\x1b\n" +
	"\ttool_args\x18\x04 \x01(\tR\btoolArgs\x12#\n" +
	"\rfinish_reason\x18\x05 \x01(\tR\ffinishReason\x12\x19\n" +
	"\bis_final\x18\x06 \x01(\bR\aisFinal\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x128\n" +
	"\n" +
	"tool_calls\x18\b \x03(\v2\x19.zhitongagent.v1.ToolCallR\ttoolCalls\x12,\n" +
	"\x05usage\x18\t \x01(\v2\x16.zhitongagent.v1.UsageR\x05usage\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"model_name\x18\v \x01(\tR\tmodelName\x12D\n" +
	"\x11additional_kwargs\x18\f \x01(\v2\x17.google.protobuf.StructR\x10additionalKwargs\x12D\n" +
	"\x11response_metadata\x18\r \x01(\v2\x17.google.protobuf.StructR\x10responseMetadata\x12>\n" +
	"\x0eusage_metadata\x18\x0e \x01(\v2\x17.google.protobuf.StructR\rusageMetadata2\xba\x01\n" +
	"\fZhitongAgent\x12S\n" +
	"\n" +
	"ChatStream\x12\".zhitongagent.v1.ChatStreamRequest\x1a\x1f.zhitongagent.v1.StreamResponse0\x01\x12U\n" +
	"\vAgentStream\x12#.zhitongagent.v1.AgentStreamRequest\x1a\x1f.zhitongagent.v1.StreamResponse0\x01B.Z,github.com/abyssferry/zhitong_go_agent/pb;pbb\x06proto3"

var (
	file_zhitongAgent_proto_rawDescOnce sync.Once
	file_zhitongAgent_proto_rawDescData []byte
)

func file_zhitongAgent_proto_rawDescGZIP() []byte {
	file_zhitongAgent_proto_rawDescOnce.Do(func() {
		file_zhitongAgent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_zhitongAgent_proto_rawDesc), len(file_zhitongAgent_proto_rawDesc)))
	})
	return file_zhitongAgent_proto_rawDescData
}

var file_zhitongAgent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_zhitongAgent_proto_goTypes = []any{
	(*Message)(nil),            // 0: zhitongagent.v1.Message
	(*ToolCallFunction)(nil),   // 1: zhitongagent.v1.ToolCallFunction
	(*ToolCall)(nil),           // 2: zhitongagent.v1.ToolCall
	(*ToolFunction)(nil),       // 3: zhitongagent.v1.ToolFunction
	(*ToolDefinition)(nil),     // 4: zhitongagent.v1.ToolDefinition
	(*StreamOptions)(nil),      // 5: zhitongagent.v1.StreamOptions
	(*Usage)(nil),              // 6: zhitongagent.v1.Usage
	(*ChatStreamRequest)(nil),  // 7: zhitongagent.v1.ChatStreamRequest
	(*AgentStreamRequest)(nil), // 8: zhitongagent.v1.AgentStreamRequest
	(*StreamResponse)(nil),     // 9: zhitongagent.v1.StreamResponse
	(*structpb.Struct)(nil),    // 10: google.protobuf.Struct
}
var file_zhitongAgent_proto_depIdxs = []int32{
	2,  // 0: zhitongagent.v1.Message.tool_calls:type_name -> zhitongagent.v1.ToolCall
	1,  // 1: zhitongagent.v1.ToolCall.function:type_name -> zhitongagent.v1.ToolCallFunction
	10, // 2: zhitongagent.v1.ToolFunction.parameters:type_name -> google.protobuf.Struct
	3,  // 3: zhitongagent.v1.ToolDefinition.function:type_name -> zhitongagent.v1.ToolFunction
	10, // 4: zhitongagent.v1.Usage.prompt_tokens_details:type_name -> google.protobuf.Struct
	10, // 5: zhitongagent.v1.Usage.completion_tokens_details:type_name -> google.protobuf.Struct
	2,  // 6: zhitongagent.v1.StreamResponse.tool_calls:type_name -> zhitongagent.v1.ToolCall
	6,  // 7: zhitongagent.v1.StreamResponse.usage:type_name -> zhitongagent.v1.Usage
	10, // 8: zhitongagent.v1.StreamResponse.additional_kwargs:type_name -> google.protobuf.Struct
	10, // 9: zhitongagent.v1.StreamResponse.response_metadata:type_name -> google.protobuf.Struct
	10, // 10: zhitongagent.v1.StreamResponse.usage_metadata:type_name -> google.protobuf.Struct
	7,  // 11: zhitongagent.v1.ZhitongAgent.ChatStream:input_type -> zhitongagent.v1.ChatStreamRequest
	8,  // 12: zhitongagent.v1.ZhitongAgent.AgentStream:input_type -> zhitongagent.v1.AgentStreamRequest
	9,  // 13: zhitongagent.v1.ZhitongAgent.ChatStream:output_type -> zhitongagent.v1.StreamResponse
	9,  // 14: zhitongagent.v1.ZhitongAgent.AgentStream:output_type -> zhitongagent.v1.StreamResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_zhitongAgent_proto_init() }
func file_zhitongAgent_proto_init() {
	if File_zhitongAgent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zhitongAgent_proto_rawDesc), len(file_zhitongAgent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_zhitongAgent_proto_goTypes,
		DependencyIndexes: file_zhitongAgent_proto_depIdxs,
		MessageInfos:      file_zhitongAgent_proto_msgTypes,
	}.Build()
	File_zhitongAgent_proto = out.File
	file_zhitongAgent_proto_goTypes = nil
	file_zhitongAgent_proto_depIdxs = nil
}
